menu:
  Home: /
  Archives: /archives
  Links: /links

## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml
 
## 网站公告设置
notification: |-
            <p>主题Snippet v1.2.0版本已经上线！欢迎更新~ <br/>
            主题下载：<a href="https://github.com/shenliyang/hexo-theme-snippet" title="fork me" target="_blank">Snippet主题</a> <br/>
            <hr/>接受贡献，包括不限于提交问题与需求，修复代码。接受贡献，包括不限于提交问题与需求，修复代码欢迎Pull Request<br/>支持主题：<a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star一下</a>
            </p>

## 社交设置
social:
 - name: Github
   icon: '&#xeee2;'
   href: //github.com/praming
 - name: 邮箱
   icon: '&#xe69f;'
   href: mailto:i@praming.cn
 - name: 微信
   icon: '&#xe7e5;'
   href: 34721974
 - name: 微博
   icon: '&#xe629;'
   href: //weibo.com/praming
 - name: RSS
   icon: '&#xe6ee;'
   href: /atom.xml

## 主题评论

### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 来必力
livere: 
  enable: true
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 

### Disqus评论
disqus:
  enable: false
  shortname: 
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid: 
  conf: 

## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics:

### 百度统计
baidu_analytics: 1d283676d7e81d10054b06f70a90decf

### 谷歌统计
google_analytics: 

### 腾讯分析
tencent_analytics: 

### 百度文章推送
baidu_push:

## ICP备案号:
icp: 豫ICP备10206454号-2

## 开启Hosted by Coding Pages标识
coding_pages: true

## 友链设置
links:
  - 个人博客: http://www.shenliyang.com