menu:
  Home: /
  Archives: /archives
  Links: /links
 
## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml
 
## 网站公告设置
notification: |-
            <p>主题Ice V1.0 版本已经上线！欢迎使用~ <br/>
            主题下载：<a href="https://github.com/praming/hexo-theme-Ice" title="fork me" target="_blank">Ice 主题</a>&nbsp;&nbsp;&nbsp;&nbsp;详细的使用文档请点击:<a href="https://github.com/praming/hexo-theme-Ice" title="fork me" target="_blank">使用说明</a>.<br/>
            <hr/>接受贡献，包括不限于提交问题与需求，修复代码。接受贡献，包括不限于提交问题与需求，修复代码欢迎Pull Request<br/>支持主题：<a href="https://github.com/praming/hexo-theme-Ice/stargazers"  target="_blank">Star一下</a>
            </p>

## 社交设置
social:
 - name: Github
   icon: '&#xeee2;'
   href: //github.com/praming
 - name: 邮箱
   icon: '&#xe69f;'
   href: mailto:i@praming.cn
 - name: 微信
   icon: '&#xe7e5;'
   href: 34721974
 - name: 微博
   icon: '&#xe629;'
   href: //weibo.com/praming
 - name: RSS
   icon: '&#xe6ee;'
   href: /atom.xml

# add post views
leancloud_visitors:
  enable: true
  app_id: hESKc51xYeFsVNctLcYmpOS1-gzGzoHsz
  app_key: IPK32hWXJh8WMPOW4xEqsA9V

## 主题评论

### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 来必力
livere: 
  enable: false
  livere_uid: 

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 

### Disqus评论
disqus:
  enable: false
  shortname: 
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: true
  appid: cytsbYV5p
  conf: prod_5db6bea920c9a0d149cedeab44860234
  
# Valine评论
# 需要 https://leancloud.cn 的appid和appkey 
# 更多请登录 https://valine.js.org
valine:
  enable: false
  appid:  hESKc51xYeFsVNctLcYmpOS1-gzGzoHsz  # 你的appid
  appkey: IPK32hWXJh8WMPOW4xEqsA9V  # 你的appkey
  notify: false # 开启评论邮件回复 , https://github.com/xCss/Valine/wiki
  verify: false # 开启验证码
  placeholder: ヾﾉ≧∀≦)o来啊，快活啊! # 评论框显示内容
  avatar: monsterid # gravatar 头像类型
  guest_info: nick,mail,link # 评论者需要填写的属性
  pageSize: 10 # 每页评论数


## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics:

### 百度统计
baidu_analytics: 1d283676d7e81d10054b06f70a90decf

### 谷歌统计
google_analytics: 

### 腾讯分析
tencent_analytics: 

### 百度文章推送
baidu_push:

## ICP备案号:
icp: 豫ICP备10206454号-2

## 开启Hosted by Coding Pages标识
coding_pages: true

## 友链设置
links:
  - 个人博客: http://www.shenliyang.com
  

